import React from 'react';
import { ChatScreenProps } from './types';
declare const ChatScreen: React.FC<ChatScreenProps>;
export { VoiceRecorder, type VoiceRecorderProps, } from './components/VoiceRecorder/VoiceRecorder';
export { VoiceRecordingGesture, type VoiceRecordingGestureProps, } from './components/VoiceRecorder/VoiceRecordingGesture';
export { VoiceRecorderFlow, type RecordingState, type VoiceRecorderFlowAudio, type VoiceRecorderFlowProps, } from './components/VoiceRecorder/VoiceRecorderFlow';
export { LongPressOverlay, MessageActionsPopover, MessageActionsSheet, tryCopyMessage, } from './components/MessageActions';
export { InlineReply, ReplyPreview, SwipeableMessage, } from './components/Reply';
export { SelectIcon } from './assets/Icons/SelectIcon';
export type { ChatScreenProps, DateSeparatorTheme, Message, MessageActionAnchor, MessageActionFlags, MessageActionIconComponents, MessageActionId, MessageActionLabels, MessageActionUIProps, MessageFileAttachment, MessageMediaItem, MessageReply, PreviewAttachment, RecordingResult, RecordingUIProps, ReplyConfig, ReplyStyleOverrides, ReplyUIProps, SelectionUIProps, SwipeReplyUIProps, VoiceRecorderConfig, VoiceRecorderExposedState, VoiceRecorderStyleOverrides, } from './types';
export type { ChatListItem } from './utils/dateSeparator';
export { buildChatListItems, diffCalendarDays, formatDateSeparatorLabel, getDayKey, getDefaultDateSeparatorLocale, parseMessageDate, truncateToLocalMidnight, } from './utils/dateSeparator';
export default ChatScreen;
