import React, { ReactNode } from 'react';
import { TextStyle, ViewStyle } from 'react-native';
import { Gesture } from 'react-native-gesture-handler';
import { useAnimatedStyle, type SharedValue } from 'react-native-reanimated';
interface RecordingBarProps {
    duration: number;
    isPaused: boolean;
    composedGesture: ReturnType<typeof Gesture.Race>;
    micWrapperStyle: ReturnType<typeof useAnimatedStyle>;
    pausePulseStyle: ReturnType<typeof useAnimatedStyle>;
    recDotStyle: ReturnType<typeof useAnimatedStyle>;
    waveTick: SharedValue<number>;
    onCancelPress: () => void;
    onTogglePause: () => void;
    backgroundColor: string;
    timerColor: string;
    waveformColor: string;
    deleteIconColor: string;
    pauseIconColor: string;
    primaryColor: string;
    micSize: number;
    iconSize: number;
    inputBarHeight: number;
    waveCount: number;
    enableWaveform: boolean;
    renderDeleteIcon?: () => ReactNode;
    renderPauseIcon?: () => ReactNode;
    renderPlayIcon?: () => ReactNode;
    renderSendIcon?: () => ReactNode;
    renderWaveform?: () => ReactNode;
    containerStyleOverride?: ViewStyle;
    barStyleOverride?: ViewStyle;
    timerTextStyle?: TextStyle;
    waveformStyle?: ViewStyle;
    trashButtonStyle?: ViewStyle;
    sendButtonStyle?: ViewStyle;
}
export declare const RecordingBar: React.FC<RecordingBarProps>;
export {};
