import type { ReactNode } from 'react';
import type { TextStyle, ViewStyle } from 'react-native';
export type RecordingState = 'IDLE' | 'RECORDING_TAP' | 'RECORDING_HOLD' | 'LOCKED_RECORDING' | 'SENDING' | 'CANCELLED';
export declare const STATE_IDLE = 0;
export declare const STATE_TAP = 1;
export declare const STATE_HOLD = 2;
export declare const STATE_LOCKED = 3;
export declare const STATE_SENDING = 4;
export declare const STATE_CANCELLED = 5;
export declare function stateToInt(s: RecordingState): number;
export interface VoiceRecorderFlowAudio {
    duration: number;
}
export interface VoiceRecorderFlowProps {
    primaryColor?: string;
    backgroundColor?: string;
    holdPillBackground?: string;
    timerColor?: string;
    microphoneColor?: string;
    lockColor?: string;
    waveformColor?: string;
    deleteIconColor?: string;
    cancelTextColor?: string;
    chevronColor?: string;
    pauseIconColor?: string;
    lockPillBackground?: string;
    inputBarHeight?: number;
    micSize?: number;
    holdMicScale?: number;
    iconSize?: number;
    lockIconSize?: number;
    enableLockRecording?: boolean;
    enableSlideToCancel?: boolean;
    enableWaveform?: boolean;
    lockSlideDistance?: number;
    cancelSlideDistance?: number;
    waveCount?: number;
    renderInputPill?: () => ReactNode;
    renderMicIcon?: () => ReactNode;
    renderSendIcon?: () => ReactNode;
    renderLockIcon?: () => ReactNode;
    renderArrowIcon?: () => ReactNode;
    renderDeleteIcon?: () => ReactNode;
    renderPauseIcon?: () => ReactNode;
    renderPlayIcon?: () => ReactNode;
    renderWaveform?: () => ReactNode;
    containerStyle?: ViewStyle;
    barStyle?: ViewStyle;
    timerTextStyle?: TextStyle;
    slideTextStyle?: TextStyle;
    waveformStyle?: ViewStyle;
    lockPillStyle?: ViewStyle;
    trashButtonStyle?: ViewStyle;
    sendButtonStyle?: ViewStyle;
    fontFamily?: string;
    headerSlot?: ReactNode;
    showSendButton?: boolean;
    onSendPress?: () => void;
    sendButtonBackgroundColor?: string;
    sendButtonIconColor?: string;
    onRecordingStart?: () => void;
    onRecordingStop?: () => void;
    onSend?: (audio: VoiceRecorderFlowAudio) => void;
    onDelete?: () => void;
    onLock?: () => void;
    onCancel?: () => void;
    onPauseRecording?: () => void;
    onResumeRecording?: () => void;
    onStateChange?: (state: RecordingState) => void;
}
